config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#home"
  get "/profile", to: 'pages#profile'

  resources :gardens, only: [:index, :new, :create, :show, :update, :edit] do
    resources :plants, only: [:show, :create]
  end

  resources :plants, only: [:index, :show, :create,:new, :destroy]

  get "/blog", to: 'articles#index'
  resources :articles, except: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_rich_text :rich_body
  has_one_attached :photo
end

app/models/garden.rb
class Garden < ApplicationRecord

  # Attractions
  belongs_to :user
  has_many :plants, dependent: :destroy
  has_one_attached :photo

  # Validations
  validates :name, presence: true
end

app/models/plant.rb
class Plant < ApplicationRecord

  # Attractions
  belongs_to :garden, optional: true
  has_one_attached :photo

  # Validations
  #validates :nickname, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  # Attractions
  has_one :garden
  has_many :plants, through: :garden
  def email_required?
    false
  end

  def email_changed?
    false
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :description, :email])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :description, :email])
  end

  def profile
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article, notice: 'Article créé'
    else
      render :new
    end
  end

  def update
    if @article.update(article_params)
      redirect_to @article, notice: 'Article modifié'
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to root_path, notice: 'Article détruit'
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :rich_body, :photo)
  end
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  def index
    @garden = Garden.all
  end

  def show
    @garden = Garden.find(params[:id])
    @plant = Plant.new(garden: @garden)
  end

  def new
    @garden = Garden.new
  end

  def create
    @garden = Garden.create(garden_params)
    @garden.user = current_user
    if @garden.save
      redirect_to garden_path(@garden)
      flash[:success] = 'Bienvenue à bord ! Vous pouvez maintenant ajouter des plantes à votre jardin 🌱'
    else
      render :new
    end
  end

  def edit
    @trip = Trip.find(params[:id])
  end

private

  def garden_params
    params.require(:garden).permit(:name, :photo, :plant_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @user
    @plants = Plant.all
    @gardens
    @photo
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController

  skip_before_action :authenticate_user!, only: :show

  def index
    @plant = Plant.all
  end

  def show
    @plant = Plant.find(params[:id])
  end

  def new
    @garden = Garden.find(params[:garden_id])
    @plant = Plant.new
  end

  def create
    @garden = Garden.find(params[:garden_id])

    @plant = Plant.new(plant_params)
    @plant.garden = @garden

    if @plant.save!
      redirect_to garden_path(@garden)
      flash[:success] = 'Belle plante ! Que le temps la rende belle et vigoureuse 🌵'
    else
      render :new
    end
  end

  def edit
    @plant = Plant.find(params[:id])
  end

  def destroy
    @plant = Plant.find(params[:id])
    @plant.garden
    @plant.destroy
    redirect_to garden_path(@plant.garden)
  end

  def is_gonna_die
    @plant = Plant.find(params[:id])
    @plant.water? flash[:alert] = "N'oubliez pas d'arroser votre plante aujourd'hui 💦"
  end
private

  def plant_params
    params.require(:plant).permit(:nickname, :science_name, :origin, :genre, :advice, :story, :photo, :garden_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/articles/_form.html.erb
<%= simple_form_for(@article) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title, :label => "Titre" %>
     <%= f.input :photo, as: :file, input_html: { multiple: true } %>
  </div>
  <div class="form-inputs">
    <%= f.rich_text_area :rich_body, :placeholder => "Écrire ici..." %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Poster Article", class: "btn btn-success" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class="container">
  <h1>Modifier Article</h1>

  <%= render 'form', article: @article %>

  <%= link_to 'Voir', @article %> |
  <%= link_to 'Retour', root_path %>
</div>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<h1>Articles</h1>
<!-- <table> -->
<!--   <thead>
    <tr>
      <th>Titre</th>
      <th>Contenu</th>
      <th colspan="3"></th>
    </tr>
  </thead> -->
<!--   <tbody> -->
    <% @articles.each do |article| %>
<!--       <tr> -->
      <div class="article">
        <img url="<%= cl_image_tag article.photo if article.photo.attached? %>">
        <div class="article-info">
          <h2><%= article.title %></h2>
          <hr>
          <p><%= article.rich_body %></p>
        </div>
        <div class="article-params">
          <p><%= link_to 'Voir', article %></p>
          <p><%= link_to 'Modifier', edit_article_path(article) %></p>
          <p><%= link_to 'Détruire', article, method: :delete, data: { confirm: '🧙‍♂️En es-tu vraiment sûr Frodon?' } %></p>
        </div>
      </div>
<!--       </tr> -->
    <% end %>
<!--   </tbody>
</table> -->
<br>
</div>
<div class="btn btn-flat">
<%= link_to 'Nouvel Article', new_article_path %>
</div>

app/views/articles/new.html.erb
<div class="container">
  <h1>Ecris ton article</h1>

  <%= render 'form', article: @article %>

  <%= link_to 'Retour', root_path %>
</div>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <p>
    <strong>Titre:</strong>
    <%= @article.title %>
  </p>

  <p>
    <strong>Contenu:</strong>
    <%= @article.rich_body %>
  </p>

  <%= cl_image_tag @article.photo if @article.photo.attached? %>
  <%= cl_image_tag @article.photo %>

  <%= link_to 'Modifier', edit_article_path(@article) %> |
  <%= link_to 'Retour', root_path %>
</div>

app/views/gardens/_plant_card.html.erb
<div class="card-plant">
  <%= link_to plant.nickname, plant_path(plant) %>
  <%= link_to "+", plant_path(plant), method: :delete, data: { confirm: "Are you sure?" }, class: "card-remove-link" %>
</div>

app/views/gardens/new.html.erb
<div class="container">
<h1 class="mb-5 mt-3">Votre nouveau petit jardin secret 🏡</h1>
  <%= simple_form_for(@garden) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-flat" %>
  </div>
  <% end %>
</div>

app/views/gardens/show.html.erb
<div class="container">
  <h1> <%= @garden.name %> </h1>

  <div class="card">
    <% @garden.plants.each do |plant| %>
      <%= render "gardens/plant_card", plant: plant %>
    <% end %>
  </div>

  <div class="d-flex align-center">
    <h3 class="text-center">Ajoute une plante 🌿</h3>
      <%= simple_form_for [@garden, @plant] do |f| %>
      <%#= f.input :garden %>
      <%= f.input :nickname, placeholder: "Belle plante" %>
      <%= f.input :photo, as: :file %>
      <div class="form-actions">
        <%= f.submit "Add", class: "btn btn-flat" %>
      </div>
      <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FloreProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.pexels.com/photos/1903970/pexels-photo-1903970.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940);">
    <h1>Make Plants Great Again !</h1>
    <div class="d-flex justify-content-start" id="btn">
      <span class="noselect">Create your Garden</span>
      <div id="circle"></div>
    </div>
</div>
<div class="container">
  <h2 class="text-center mt-3">Comment ça marche ?</h2>
  <div class="info">
    <div class="bloc">
      <%= image_tag "green.svg"%>
      <h4>Créer ton jardin</h4>
      <p>Manage et compose ton jardin virtuel</p>
    </div>
    <div class="bloc">
      <img src="images/cactus.svg" alt="">
      <%= image_tag "cactus.svg"%>
      <h4>Ajoute tes plantes</h4>
      <p>Donne un petit nom à tes plantes</p>
    </div>
    <div class="bloc">
      <%= image_tag "mario.svg"%>
      <h4>Sauve tes plantes de la soif</h4>
      <p>Reçois des notifications pour garder en vie tes plantes</p>
    </div>
  </div>
</div>
<h2>Découvrez de nouvelles plantes</h2>
<div class="cards">
  <% @plants.each do |plant| %>
  <div class="card">
    <%= link_to plant_path(plant) do %>
    <h3><%= plant.science_name %></h3>
    <% if plant.photo.attached? %>
    <%=  cl_image_tag plant.photo.key %>
    <% end %>
    <% end %>
  </div>
  <% end %>
</div>

app/views/plants/index.html.erb
<h1>Trouve la plante de tes rêves 🌿</h1>

app/views/plants/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.pexels.com/photos/1924867/pexels-photo-1924867.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940);">
<h1><%= @plant.science_name %></h1>
  <div class="container card">
    <h2>La vie de <%= @plant.nickname %></h2>
    <p><strong>Origine :</strong> <%= @plant.origin %></p>
    <p><strong>Type :</strong> <%= @plant.genre %></p>
    <p><strong>Histoire :</strong> <%= @plant.story %></p>
    <p><strong>Conseils :</strong> <%= @plant.advice %></p>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "https://image.flaticon.com/icons/svg/3043/3043782.svg" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Blog", "/blog", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/junkiesan", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item active">
          <%= link_to "Blog", "/blog", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>